modemLogsLocalEndpoint: http://192.168.100.1/cmLogsData.htm
modemStatsLocalEndpoint: http://192.168.100.1/cmSignalData.htm

echoResponseTracerJobCronExpression: 0 */15 * ? * *
cableModemLogScraperJobCronExpression: 0 0 * ? * *
cableModemStatisticsScraperJobCronExpression: 0 0 1 * * ?

echoRequestsPerEndpoint: 5
echoResponseEndpoints:
- 141.142.2.2
- 8.8.8.8
- 4.2.2.2