modemLogsLocalEndpoint: http://192.168.100.1/cmLogsData.htm
modemStatsLocalEndpoint: http://192.168.100.1/cmSignalData.htm

echoRequestsPerEndpoint: 5
echoRequestTimeoutInMilliseconds: 5000
echoResponseEndpoints:
- 141.142.2.2
- 8.8.8.8
- 4.2.2.2