modemLogsLocalEndpoint: http://192.168.100.1/cmLogsData.htm
modemStatsLocalEndpoint: http://192.168.100.1/cmSignalData.htm

cableModemLogScraperJobExecutionIntervalInHours: 24
cableModemStatisticsScraperJobExecutionIntervalInHours: 6
echoResponseTracerJobExecutionIntervalInHours: 1
dynamoDBQueueFlushJobExecutionIntervalInMinutes: 30

echoRequestsPerEndpoint: 5
echoResponseEndpoints:
- 141.142.2.2
- 8.8.8.8
- 4.2.2.2